# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6f8f5ab6bf1110e0c4f1033aa9b5251272d6fdb18dd139ab5304b36b2018d43afec288186f262b11927570c62efe6bd87c537b849174ad8d3d75a91f7038e29

test:
  secret_key_base: e9c39890fb67cb6aa6290e193db88f8f32719888c69be93858f9929df251fc3a8cc93ba1753c5f2b1d4487adae6ec0a06ed4c28d382e2362e8203bc8c6919de9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
